#!/bin/bash

if whoami | grep -q 'u0_'; then # Termux

  # init
  clear
  echo -en '\e[33mWARNING : this script was made for fresh TERMUX installs. Otherwise, expect your system to break.\e[0m\n\nContinue ? '
  read x; [ "$x" != y ] && echo && exit
  [ ! -d ~/storage ] && termux-setup-storage
  touch ~/.hushlogin

  # update
  echo -en '\nupdate ? '; read x; [ "$x" = y ] && \
    apt update -o DPkg::Options::="--force-confnew" -y && \
    apt upgrade -o DPkg::Options::="--force-confnew" -y && \
    pkg update -o DPkg::Options::="--force-confnew" -y && \
    pkg upgrade -o DPkg::Options::="--force-confnew" -y
  mkdir -p ~/.temp ~/.temp/trash
  rm ~/storage/ -rf

  # packages
  echo -en "\ninstall packages? : "
  read x; [ "$x" = y ] && \
  apt install wget nano python3 p7zip \
      proot-distro git wget man htop tree \
      nodejs ffmpeg file lynx jq bc whois \
      imagemagick potrace \
      -o DPkg::Options::="--force-confnew" -y && \
      npm install peerflix -g

  # backup
  echo -en "\nextract backup? : "
  read x; echo "$x" | egrep -q '.{8,}' && \
    curl -# -L 'go.ly/bkp-prv' -o backup.7z && \
    apt install -y p7zip && \
    7z x backup.7z -o"$HOME" -p"$x" -y && \
    rm -rf ~/backup.7z
  [ "$x" = y ] && \
    curl -# -L 'go.ly/bkp-pub' -o backup.7z && \
    apt install -y p7zip && \
    7z x backup.7z -o"$HOME" -y && \
    rm -rf ~/backup.7z

  # java
  echo -en "\ninstall java? : "
  read x; [ "$x" = y ] && \
  curl -s 'https://raw.githubusercontent.com/MasterDevX/java/master/installjava' -o javainstall && \
  bash javainstall && \
  rm -rf javainstall ~/.profile

  # pip
  echo -en "\ninstall pip and its packages? : "
  read x; [ "$x" = y ] && \
  python3 -m pip install --upgrade pip && \
  pip install yt-dlp spotdl

  # vm
  echo -en "\ninstall ubuntu vm? : "
  read x; [ "$x" = y ] && \
  apt install proot-distro && \
  proot-distro install ubuntu

  # end
  wait; pkill -4 bash

elif [[ $(arch-chroot 2>&1) == '==> ERROR: No chroot directory specified' ]]; then # arch iso

  # init
  clear
  read -p $'\e[33mWARNING : this script was made for ARCH ISOs. Otherwise, expect your system to break.\e[0m\nContinue ? (default=n) ' x
  [ "$x" = chroot ] && cp "$0" /mnt/root/install && arch-chroot /mnt ./root/install && exit
  [ "$x" != y ] && echo -e '\nAbording...\n' && exit

  # internet check
  echo
  if ping google.com -c1 >/dev/null 2>&1; then
    echo '> Connected to the internet'
  else
    echo -e '> \e[31mERROR : Not connected to the internet. Please verify your connection and try again\e[0m\n'
    exit
  fi

  # sync date
  timedatectl set-ntp true
  while timedatectl status | grep -q 'System clock synchronized: no'; do
    [ "$tries" = 20 ] && echo 'Time clock failed to synchronize... && exit'
    ((tries++))
    sleep 0.5
  done
  echo -e '> Time clock successfully synchronized\n'

  # disk selection
  while true; do
    echo -e 'Disks for installation :\n'
    diskList=$(fdisk -l)
    readarray -t disks <<< $(egrep -o '^Disk /dev/[^,]+' <<< "$diskList" | grep -v '^Disk /dev/loop')
    for ((i=0; i < "${#disks[@]}"; i++)); do
      choiceList[i]=$(echo "[$i] - $(grep -b1 "${disks[i]}" <<< "$diskList" | tail -n 1 | grep -Po '(?<=: ).+' | sed 's: *$::g') - ${disks[i]:6}")
    done
    printf '%s\n' "${choiceList[@]}"
    echo
    read -p 'Option (m for more info) (default=0) : ' x
    echo
    if [ "$x" = m ]; then
      clear && fdisk -l
      continue
    elif [ "$x" = '' ]; then
      x=0
    fi
    disk="${disks[x]:6}"
    if [[ -n "$disk" && "$x" =~ [0-9]+ ]]; then
      disk="/$(egrep -o '^[^: ]+' <<< "$disk")"
      echo -e "> \e[32mSelected ${choiceList[x]:6}\e[0m\n"
      break
    else
      echo -e "> \e[31mERROR : Invalid selection\e[0m\n"
    fi

  done

  # partitionning
  read -p $'Format ALL disk and setup partitions ?\n\e[31m(WARNING: THERE IS NO COMMING BACK)\e[0m (default=n) : ' x
  [ "$x" != y ] && echo -e '\nAbording...\n' && exit
  echo
  dd if=/dev/zero of="$disk" bs=512 count=1 conv=notrunc >> log 2>&1
  echo -e 'g\nn\n\n\n+550M\nn\n\n\n+2G\nn\n\n\n\nt\n1\n1\nt\n2\n19\nw' | fdisk "$disk" >> log 2>&1
  fdisk -l "$disk" --color=always | egrep -v -e '^Units' -e '^Sector size' -e '^I/O' -e '^Disk identifier'
  [ "$x" != y ] && echo -e '\nAbording...\n' && exit

  # filesystems
  efi=$(fdisk -l "$disk" | tail -n 3 | grep 'EFI System' | awk '{print $1}')
  swap=$(fdisk -l "$disk" | tail -n 3 | grep 'Linux swap' | awk '{print $1}')
  filesystem=$(fdisk -l "$disk" | tail -n 3 | grep 'Linux filesystem' | awk '{print $1}')
  read -p $'\nMake filesystems ? (default=y) '
  [ "$x" = e ] && echo -e '\nAbording...\n' && exit
  [ "$x" = n ] && echo -e '\nAbording...\n' && exit
  echo 'Please wait a few minutes...'
  umount -q -l "$filesystem"
  mkfs.fat -F32 "$efi" >> log 2>&1
  mkswap "$swap" >> log 2>&1
  swapon "$swap" >> log 2>&1
  mkfs.ext4 "$filesystem" >> log 2>&1
  mount "$filesystem" /mnt
  echo -e 'Done\n'

  # arch-chroot
  read -p $'Install base packages ? (default=y) : ' x
  [ "$x" = e ] && echo -e '\nAbording...\n' && exit
  [ "$x" = n ] && echo -e '\nAbording...\n' && exit
  pacstrap /mnt base linux-firmware nano sudo grub efibootmgr dosfstools os-prober mtools networkmanager
  genfstab -U /mnt >> /mnt/etc/fstab
  hwclock --systohc

  # chroot
  read -p $'\nChroot in ? (default=y) : ' x
  [ "$x" = e ] && echo -e '\nAbording...\n' && exit
  [ "$x" = n ] && echo -e '\nAbording...\n' && exit
  cp "$0" /mnt/root/install
  echo "$efi" > /mnt/root/.efiDisk
  arch-chroot /mnt ./root/install "$efi"
  cat log >> /mnt/root/log

  # reboot
  read -p $'\nUnmount and reboot ? (default=y) : ' x
  [ "$x" = e ] && echo -e '\nAbording...\n' && exit
  if [[ "$x" = n ]]; then
    echo -e "> \e[32mSkipped\e[0m"
  else
    umount -l "$filesystem"
    reboot now
  fi
  echo -e "\n\e[32mScript finished!\e[0m"
  echo -e "INFO : Please do 'umount -l $filesystem' before rebooting\n"

elif [[ $(uname -a) =~ 'archiso' ]]; then # arch chroot

  # init
  echo -e "\nINFO : In chroot, you cannot CTRL+C\nTo exit, \e[31mDO NOT CTRL+Z\e[0m (or it breaks)\nInstead, anwser 's' (skip) or 'e' (exit) to any question"

  # region
  while true; do
    echo
    ls /usr/share/zoneinfo/
    echo
    read -p 'Region ? (default=Europe) ' x
    [ "$x" = e ] && echo -e '\nAbording...\n' && exit
    [ "$x" = '' ] && x=Europe
    if [[ "$x" = n ]]; then
      echo -e "> \e[31mSkipped\e[0m"
      break
    elif [[ -d /usr/share/zoneinfo/"$x" && -n "$x" ]]; then
      echo -e "> \e[32mSelected $x\e[0m"
      break
    else
      echo -e '\n> \e[31mERROR : Invalid input\e[0m'
    fi
  done

  # city
  while true; do
    echo
    ls /usr/share/zoneinfo/"$x"
    echo
    read -p 'Location? (default=Paris) ' y
    [ "$y" = e ] && echo -e '\nAbording...\n' && exit
    [ "$y" = '' ] && y=Paris
    if [[ "$x" = n ]]; then
      echo -e "> \e[31mSkipped\e[0m"
      break
    elif [[ -f /usr/share/zoneinfo/"$x"/"$y" ]]; then
      echo -e "> \e[32mSelected $y\e[0m"
      break
    else
      echo -e '\n> \e[31mERROR : Invalid input\e[0m'
    fi
  done
  ln -sf /usr/share/zoneinfo/"$x"/"$y" /etc/localtime

  # locale
  while true; do
    echo
    cat /etc/locale.gen | egrep -o '[a-z]+_[A-Z]{2}' | sort | uniq | column
    echo
    read -p 'Locale? (default=en_US) ' x
    [ "$x" = e ] && echo -e '\nAbording...\n' && exit
    [ "$x" = '' ] && x=en_US
    if [[ "$x" = n ]]; then
      echo -e "> \e[31mSkipped\e[0m"
      break
    elif [[ -n $(egrep "^#$x" /etc/locale.gen) && "$x" =~ [a-z]+_[A-Z]{2} ]]; then
      selected=$(grep "^#$x" /etc/locale.gen | grep UTF | head -n 1)
      if [[ -f /etc/locale.gen.bak ]]; then
        cp /etc/locale.gen.bak /etc/locale.gen
      else
        cp /etc/locale.gen /etc/locale.gen.bak
      fi
      result=$(sed "s:$selected:${selected:1}:" /etc/locale.gen)
      echo "$result" >> /etc/locale.gen
      egrep -o "^[a-z]+[A-Z]{2}" /etc/locale.gen
      locale-gen >/dev/null
      echo -e "> \e[32mApplied $(sed 's:UTF-8 UTF-8:UTF-8:' <<< $(egrep "^[a-z]+_[A-Z]{2}" /etc/locale.gen))\e[0m\n"
      break
    else
      echo -e '\n> \e[31mERROR : Invalid input\e[0m'
    fi
  done

  # hostname
  read -p 'Hostname? (default=arch) ' host
  [ "$host" = e ] && echo -e '\nAbording...\n' && exit
  [ "$host" = '' ] && host=arch
  if [[ "$host" = s ]]; then
    echo -e "> \e[31mSkipped\e[0m"
  else
    echo "$x" > /etc/hostname
    echo -e "> \e[32mHostname set as $host\e[0m"
  fi

  # root pass
  read -p $'\nRoot password? (default=root) ' x
  [ "$x" = e ] && echo -e '\nAbording...\n' && exit
  [ "$x" = '' ] && x=root
  if [[ "$x" = s ]]; then
    echo -e "> \e[31mSkipped\e[0m"
  else
    echo "root:$x" | chpasswd
    echo -e "> \e[32mPassword for "root" user set\e[0m"
  fi

  # user
  read -p $'\nUser name? (default=user) ' user
  [ "$user" = e ] && echo -e '\nAbording...\n' && exit
  [ "$user" = '' ] && user=user
  if [[ "$user" = s ]]; then
    echo -e "> \e[31mSkipped\e[0m"
    user=user
  else
    useradd -m "$user" 2>/dev/null && \
    usermod -aG wheel,audio,video,optical,storage "$user"
    echo -e "> \e[32mAdded user \"$user\"\e[0m"
  fi

  # user pass
  read -p $'\nUser password? (default=user) ' x
  [ "$x" = e ] && echo -e '\nAbording...\n' && exit
  [ "$x" = '' ] && x=user
  if [[ "$x" = s ]]; then
    echo -e "> \e[31mSkipped\e[0m"
  else
    echo "$user:$x" | chpasswd
    echo -e "> \e[32mPassword for "$user" user set\e[0m"
  fi

  # sudo
  read -p $'\nRequest password when user use sudo ? (default=n) ' x
  [ "$x" = e ] && echo -e '\nAbording...\n' && exit
  if [[ "$x" = n || -z "$x" ]]; then
    echo '%wheel ALL=(ALL:ALL) NOPASSWD: ALL' | sudo EDITOR='tee -a' visudo >/dev/null
    echo -e "> \e[32mSettings saved\e[0m"
  elif [[ "$x" = y ]]; then
    echo '%wheel ALL=(ALL:ALL) ALL' | sudo EDITOR='tee -a' visudo >/dev/null
    echo -e "> \e[32mSettings saved\e[0m"
  else
    echo -e "> \e[31mSkipped\e[0m"
  fi

  # hosts
  read -p $'\nAutoconfigure hosts file ? (default=y) ' x
  [ "$x" = e ] && echo -e '\nAbording...\n' && exit
  if [[ "$x" = n ]]; then
    nano /etc/hosts
  elif [[ "$x" = y || -z "$x" ]]; then
    echo -e "127.0.0.1\tlocalhost" > /etc/hosts
    echo -e "::1\t\tlocalhost" >> /etc/hosts
    echo -e "127.0.1.1\t$user.localdomain\t$user" >> /etc/hosts
    echo -e "> \e[32mHosts file has been configured\e[0m\n"
  else
    echo -e "> \e[31mSkipped\e[0m\n"
  fi

  # grub
  read -p 'Config grub? (default=y) ' x
  [ "$x" = e ] && echo -e '\nAbording...\n' && exit
  if [[ "$x" = y || -z "$x" ]]; then
    mkdir /boot/EFI
    umount -l -q $(cat /root/.efiDisk)
    mount -q $(cat /root/.efiDisk) /boot/EFI/
    grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck >> log 2&>1
    grub-mkconfig -o /boot/grub/grub.cfg >> log 2&>1
    echo -e "> \e[32mGrub was configured\e[0m"
  else
    echo -e "> \e[31mSkipped\e[0m"
  fi

  # typical packages
  read -p $'\nUpdate and install typical packages ? (default=y) : ' x
  [ "$x" = e ] && echo -e '\nAbording...\n' && exit
  if [[ "$x" = y || -z "$x" ]]; then
    pacman -Syu git vim jq bc p7zip wget python3 man htop tree file lynx whois base-devel
  else
    echo -e "> \e[31mSkipped\e[0m"
  fi

  # personnal packages
  read -p $'\nInstall personnal packages (Gnome, Xorg, AMD drivers...) ? (default=n) : ' x
  [ "$x" = e ] && echo -e '\nAbording...\n' && exit
  if [[ "$x" = y ]]; then
    pacman -Syu mesa xf86-video-amdgpu vulkan-radeon libva-mesa-driver mesa-vdpau xorg xorg-xinit gnome firefox imagemagick potrace ffmpeg npm go
#    git clone https://aur.archlinux.org/yay-git.git
#    cd yay-git
#    makepkg -si
#    cd ..
#    rm -rf yay-git
    xinit="/home/$(ls /home | head -n 1)/.xinitrc"
    cat /etc/X11/xinit/xinitrc | head -n-5 > "$xinit"
    echo "gnome-session" >> "$xinit"
  else
    echo -e "> \e[31mSkipped\e[0m"
  fi

  # other
  systemctl enable NetworkManager >> /root/log 2>&1
  rm -f /root/install /root/.efiDisk

else

  echo 'Platform not supported yet'

fi
